CREATE TABLE IF NOT EXISTS game_scores (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  score_user INT NOT NULL DEFAULT 0,
  score_rightbot INT NOT NULL DEFAULT 0,
  score_partnerbot INT NOT NULL DEFAULT 0,
  score_leftbot INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_user_id (user_id)
);
